server:
  port: 7720

spring:
  application:
    name: re-data-input
  profiles:
    active: dev
  datasource:
    druid:
      mmysql:
        driver-class-name: @mysql.driverClass@
        url: @mysql.url@
        username: @mysql.username@
        password: @mysql.password@
        # 配置初始化大小、最小、最大
        initial-size: 5
        min-idle: 10
        max-active: 20
        # 配置获取连接等待超时的时间,ms
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 2000
        # 配置一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 900000
        validation-query: select 1
        test-while-idle: true
        test-on-return: false
        test-on-borrow: false
        keep-alive: true
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 5000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true
      moracle:
        driver-class-name: @oracle.driverClass@
        url: @oracle.url@
        username: @oracle.username@
        password: @oracle.password@
        # 配置初始化大小、最小、最大
        initial-size: 5
        min-idle: 10
        max-active: 20
        # 配置获取连接等待超时的时间,ms
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 2000
        # 配置一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 900000
        validation-query: select 1
        test-while-idle: true
        test-on-return: false
        test-on-borrow: false
        keep-alive: true
        filter:
          stat:
            log-slow-sql: true
            slow-sql-millis: 5000
            merge-sql: true
          wall:
            config:
              multi-statement-allow: true

      # 开启监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: @servlet.login.username@
        login-password: @servlet.login.password@
mybatis:
  type-aliases-package: com.joe.input.model

xxl:
  job:
    admin:
      addresses: http://localhost:4002/xxl-job-admin
    executor:
      appname: ${spring.application.name}
      port: 9998
      logpath: ./logs/data-input/jobhandler
      logretentiondays: 30
